=== Mai-Kh/The-Bench/XML/The-Bench.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT TheBench (Artist, Art, Event, Apply)>

<!ELEMENT Artist (name+, bio+, medium+, showcase?, contact?)>
  <!ELEMENT name>
  <!ELEMENT bio>
  <!ELEMENT medium>
  <!ELEMENT showcase>
  <!ELEMENT contact (email*, phone*)>
    <!ELEMENT email>
    <!ELEMENT phone>

<!ELEMENT Art (artist+, title+, subject?, date?, provenance?, location?, technique?, medium?)>
  <!ELEMENT artist>
  <!ELEMENT title>
  <!ELEMENT subject>
  <!ELEMENT date>
  <!ELEMENT provenance>
  <!ELEMENT location>
  <!ELEMENT technique>
  <!ELEMENT medium>

<!ELEMENT Event (location+, date+, time+, artists?, misc?)>
  <!ELEMENT location>
  <!ELEMENT date>
  <!ELEMENT time>
  <!ELEMENT artists>
  <!ELEMENT misc>

<!ELEMENT Apply (name+, contact+, medium?)>
  <!ELEMENT name>
  <!ELEMENT contact (email+, phone*)>
    <!ELEMENT email>
    <!ELEMENT phone>
  <!ELEMENT medium>

=== Mai-Kh/The-Bench/XML/The-Bench.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE TheBench SYSTEM "The-Bench.dtd">
<TheBench>
<Artist>
  <name>
    inser a person's name here
    </name>
  <bio>
    insert data here
    </bio>
  <medium>
    and here
    </medium>
  <showcase>
    </showcase>
  <contact>
    <email>
      </email>
    <phone>
      </phone>
  </contact>
</Artist>

<Art>
  <artist>
    </artist>
  <title>
    </title>
  <subject> <!-- (Who or What is Represented?) -->
    </subject>
  <date> <!-- (When was it made? Is it a copy of something older? Was it made before or after other similar works?) -->
    </date>
  <provenance> <!-- (Where was it made? For whom? Is it typical of the art of a geographical area?) -->
    </provenance>
  <location> <!-- (Where is the work of art now? Where was it originally located?) -->
    </location>
  <technique> <!-- How was the work created? -->
    </technique>
  <medium> <!-- What materials is the art made of? -->
    </medium>
</Art>

<Event>
  <location> </location>
  <date>  </date> <!-- and close all the rest of tags -->
  <time>
  <artists>
  <misc>
</Event>

<Apply>
  <name>
  <contact>
    <email>
    <phone>
  <medium>
</Apply>
</TheBench>
